[[main]]
  name = "About"
  pageRef = "about"
  weight = 10

[[main]]
  name = "Who We Are & Our Mission"
  pageRef = "about/mission"
  parent = "About"

[[main]]
  name = "Leadership"
  pageRef = "about/leadership"
  parent = "About"

[[main]]
  name = "ESMRMB Working Group"
  pageRef = "about/esmrmb"
  parent = "About"

[[main]]
  name = "Task Forces"
  pageRef = "taskforces"
  weight = 20

[[main]]
  name = "Resources"
  pageRef = "resources"
  weight = 30

[[main]]
  name = "Events"
  pageRef = "events"
  weight = 40

[[main]]
  name = "Join GliMR"
  pageRef = "join"
  weight = 50

[[main]]
  identifier = "search"
  weight = 99
  [main.params]
    action = "search"

[[main]]
  identifier = "locale"
  weight = 100
  [main.params]
    action = "locale"